### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by niltondiniz** [festelo/h3_dart#1]
GeneratedPluginRegistrant.m:18:4: error: unknown receiver 'H3FlutterPlugin'; did you mean 'SwiftH3FlutterPlugin'?
      [H3FlutterPlugin registerWithRegistrar:[registry registrarForPlugin:@"H3FlutterPlugin"]];
       ^~~~~~~~~~~~~~~
       SwiftH3FlutterPlugin
    In module 'h3_flutter' imported from /Users/niltondiniz/Projects/Nilton/h3_test/ios/Runner/GeneratedPluginRegistrant.m:12:
    /Users/niltondiniz/Projects/Nilton/h3_test/build/ios/Debug-iphonesimulator/h3_flutter/h3_flutter.framework/Headers/h3_flutter-Swift.h:444:12: note: 'SwiftH3FlutterPlugin' declared here
    @interface SwiftH3FlutterPlugin : NSObject <FlutterPlugin>
               ^
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

**Comment by festelo** [comment]
Should be solved in `0.2.1`. Could you please try this version?
