### ISSUE TITLE
h3_flutter on Linux, `failed to lookup symbol` error

### ISSUE THREAD

**Issue by t0mk** [festelo/h3_dart#10]
I am trying to use h3_flutter as suggested in https://github.com/festelo/h3_dart#mobile-desktop

```dart
import 'package:h3_flutter/h3_flutter.dart';
[...]

    final h3 = const H3Factory().load();

    var pol = <LatLng>[];
    try {
    pol = h3
        .h3ToGeoBoundary(BigInt.parse("0x" + h3ix))
        .map((e) => LatLng(e.lat, e.lon))
        .toList();
    } catch (e) {
      print(e);
      continue;
    }
```

I get exception:

```
flutter: Invalid argument(s): Failed to lookup symbol 'h3ToGeoBoundary': /home/tomk/myapp/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so: undefined symbol: h3ToGeoBoundary
```

Do I need to supply the so library myself? Where should I put the compiled C library, and how should I pass the path to h3_flutter initialization?

Thanks for answering!

**Comment by festelo** [comment]
Yes, unfortunately, H3 C library doesn't yet come with h3_flutter for Linux and Windows, as it comes for Android, iOS and macOS. 

You can use `h3_dart` for Linux and Windows, `h3_flutter` for other OS.

```dart
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:h3_flutter/h3_flutter.dart';
import 'package:h3_dart/h3_dart.dart' as h3_dart;

H3 loadH3() {
  if (kIsWeb || Platform.isMacOS || Platform.isAndroid || Platform.isIOS) {
    return const H3Factory().load();
  }
  if (Platform.isLinux) {
    return const h3_dart.H3Factory().byPath(
      '/path/to/library.so',
    );
  }
  throw UnsupportedError('Current OS is not supported');
}
```

https://github.com/festelo/h3_dart/tree/master/h3_dart#vm

**Comment by festelo** [comment]
The only difference between h3_flutter and h3_dart - h3_flutter comes with h3 c lib (for now only android, ios and macos) and requires project to be flutter project, while h3_dart hasn’t anything bundled and doesn’t require the project to be flutter project

**Comment by t0mk** [comment]
@festelo Thanks. Now it works for me on Linux and Web.

**Comment by t0mk** [comment]
Not sure if we should close this issue, up to you.

**Comment by festelo** [comment]
Linux is now supported in `h3_flutter` 0.6.5 - https://github.com/festelo/h3_dart/pull/25
