### ISSUE TITLE
h3_flutter 0.6.1 build fail on Android

### ISSUE THREAD

**Issue by orgeslayer** [festelo/h3_dart#13]
Thank your for responding quickly :)

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/19642747/178510357-5c2bfa5f-e2bc-42f9-a98f-3eb1c1a1e91c.png">
But same issue occurs in 0.6.1.
The reproduction occurs when you create a new project, add h3_flutter ^0.6.1 to pubspect.yml, and build it as an Android target. I'd appreciate it if you could check it again. :)

_Originally posted by @orgeslayer in https://github.com/festelo/h3_dart/issues/11#issuecomment-1181810911_

**Comment by festelo** [comment]
Hm. Yes. In 0.6.1 the example was working fine for me. But seems it was working fine, because `h3_flutter` was imported using `path dependency`, not pub.dev. 

I've released h3_flutter 0.6.2-dev, could you please confirm that it works fine for you?

**Comment by orgeslayer** [comment]
I've checked h3_flutter 0.6.2-dev, successful build on Android.
Let me close this issue. Please release it.

Thank you for responding quickly :)
