### ISSUE TITLE
help building h3 on windows 10

### ISSUE THREAD

**Issue by iulian0512** [festelo/h3_dart#16]
Hello, i have tried to build h3lib as a shared library on windows using the guide here https://github.com/uber/h3/blob/master/dev-docs/build_windows.md using the sources located in h3_ffi-0.6.0\c\h3lib but the build process produces a *.lib file (strangely) which is not usable with h3_dart.
Running h3_dart-master\h3_dart\example\ffi\src\main.dart  produces 
```
Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'h3IsValid': error code 127
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      H3C._h3IsValidPtr (package:h3_ffi/src/generated/generated_bindings.dart:615:66)
#2      H3C._h3IsValidPtr (package:h3_ffi/src/generated/generated_bindings.dart)
#3      H3C._h3IsValid (package:h3_ffi/src/generated/generated_bindings.dart:616:27)
#4      H3C._h3IsValid (package:h3_ffi/src/generated/generated_bindings.dart)
#5      H3C.h3IsValid (package:h3_ffi/src/generated/generated_bindings.dart:609:12)
#6      H3Ffi.h3IsValid (package:h3_ffi/src/h3_ffi.dart:23:17)
#7      main (file:///D:/temp/h3_dart-master/h3_dart/example/ffi/src/main.dart:7:22)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

can anyone provide a few hints to build the lib on windows ?

**Comment by festelo** [comment]
Hey! *.lib file extension is absolutely normal thing, the extension is specified in `h3_ffi/c/h3lib/CMakeLists.txt. It can be any, actually, but for tests it's simpler when extension is the same for every OS.

As I understood you successfully built the library and got `.lib` file, good.
Please use next code to load it:

```dart
import 'package:h3_ffi/h3_ffi.dart'; // this is important, import 'package:h3_flutter/h3_flutter.dart' isn't enough

final h3 = const H3FfiFactory().byPath('../path/to/your/library.lib'); // path can be relative or absolute
``` 

To keep your app cross-platform, you can use this code:

```dart
import 'package:h3_flutter/h3_flutter.dart';
import 'package:h3_ffi/h3_ffi.dart';

void main() {
  H3 h3;
  if (Platform.isWindows) {
    h3 = const H3FfiFactory().byPath('../path/to/your/windows/library.lib');
  } else {
    h3 = const H3Factory().load();
  }
}
```

**Comment by iulian0512** [comment]
i had to modify the file h3_ffi-0.6.0\c\h3lib\h3api.h and added __declspec(dllexport) to every function declaration so that because the output dynamic library will output those symbols in the resulting dynamic link library.  without this i do no think the compiled h3 library works on windows.

**Comment by festelo** [comment]
Yes, you're right. To make it work on Windows, `__declspec(dllexport)` must be added to every function or, instead, `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)` can be added to `CMakeLists.txt` file.
Here is an example - https://github.com/festelo/h3_dart/blob/master/h3_ffi/c/h3lib/CMakeLists.txt#L6.

Btw, I've just added Windows support to [h3_flutter ](https://pub.dev/packages/h3_flutter) 0.6.4 and [h3_ffi ](https://pub.dev/packages/h3_ffi) 0.6.2.
Should work out of the box with no additional setup steps.

I am going to close this issue, but be free to reopen it if you find any issues.
And thank you for your research!
