### ISSUE TITLE
polyfill is not implemented correctly in h3_ffi-0.6.0\lib\src\h3_ffi.dart

### ISSUE THREAD

**Issue by iulian0512** [festelo/h3_dart#17]
polyfill ffi implementation does not completely mirror the h3 lib polyfill that allows polygons to have holes a crucial polygon functionality.

**Comment by iulian0512** [comment]
i implemented it and created a pull request https://github.com/festelo/h3_dart/pull/18

**Comment by festelo** [comment]
Hey, thank you for the PR! Should be available in `h3_flutter` v0.6.3 and in `h3_web`, `h3_ffi`, `h3_dart` v0.6.1
