### ISSUE TITLE
h3_flutter - Support for Linux

### ISSUE THREAD

**Issue by t0mk** [festelo/h3_dart#2]
hey, thanks for a great package, it seems it's the best h3 implementation in Dart.

How likely is it to have Linux and Web support? It seems you are using the Uber's C lib. Does that mean that Linux support could be done analogically to MacOS, but Web support is not likely? Because converting/compiling the C to Javascript is not possible?

For an H3 Dart package to work on all the supported platforms, does it mean that it should be totally written in Dart? Like this is all written in Go? https://github.com/isbang/h3go

Thanks for answering and Great Work!

**Comment by festelo** [comment]
Hello! Sorry for long delay in responding.

Linux is already supported, but not so good as for other platforms. You need to get compiled h3 library. You can build the library using source code in this repository - https://github.com/festelo/h3_dart/tree/master/c/h3lib. Or you can build the library using Uber's source code - https://github.com/uber/h3, which should also work well, but it's not tested.

Tests build the library every time they launched using this script - https://github.com/festelo/h3_dart/blob/master/prepare_tests.sh

When you get h3 binary file, you can load it: 
```
import 'package:h3_flutter/h3_flutter.dart';
import 'package:h3_flutter/internal.dart';

final lib = DynamicLibrary.open('c/h3lib/build/libh3lib.dylib');
initH3C(lib);

// use h3 here
```
You can take a loot at tests - https://github.com/festelo/h3_dart/blob/master/test/h3_test.dart#L13

If you want to use the library outside of flutter apps - in dart vm, you can check my answer here - https://github.com/festelo/h3_dart/issues/3.


Flutter web is not yet supported, but maybe it will change soon :-)

**Comment by festelo** [comment]
I've created new issue for web version - https://github.com/festelo/h3_dart/issues/4

**Comment by festelo** [comment]
@t0mk let's make the title 'Support for Linux and Windows'. Because Web is already supported by h3_flutter and there was specific ticket for it, while Linux and Windows is not yet 🙂

**Comment by festelo** [comment]
Windows is now supported in `h3_flutter` 0.6.4 and `h3_ffi` 0.6.2!

**Comment by festelo** [comment]
Linux is now supported too in `h3_flutter` 0.6.5 - https://github.com/festelo/h3_dart/pull/25
