### ISSUE TITLE
Exception when run the app on android device in release mode, flutter sdk 3.10.5

### ISSUE THREAD

**Issue by PhongNgo1776** [festelo/h3_dart#26]
I got this exception when I run android app on release mode:
I run on flutter sdk: 3.10.12, sdk: '>=2.17.0 <3.0.0':
<img width="1193" alt="image" src="https://github.com/festelo/h3_dart/assets/22937922/67949b24-09f1-4a77-b465-e25e600dff8f">

When I run the app on sdk 3.0.0. it shows me:
<img width="1168" alt="image" src="https://github.com/festelo/h3_dart/assets/22937922/dcdc2b56-d419-46d0-851b-f56a9567567c">

**Comment by festelo** [comment]
Hi! Thank you for finding the issue. 
It should be fixed in this PR - https://github.com/festelo/h3_dart/pull/27

Please check h3_flutter 0.6.6 when it will be published (approx. ~15 min). 
Be free to reopen the issue if it's not fixed.
