### ISSUE TITLE
Support for Web

### ISSUE THREAD

**Issue by festelo** [festelo/h3_dart#4]
Add web support.

**Comment by festelo** [comment]
Web support has been added to `h3_dart@0.6.0-dev`, `h3_flutter@0.6.0-dev`.
https://pub.dev/packages/h3_web published

**Comment by t0mk** [comment]
@festelo wow, cool! I'm gonna test it tomorrow. Thanks!

**Comment by t0mk** [comment]
I am putting hexagon lat/lng coords to json file in my assets. There can be hundreds or thousands of the hexagons. If this works then my assets will shrink by `6x2xlen("61.46466797500582")/16`, about 12.5. There are also some other data in the (geo)json, so I expect shrink by factor of 10.

**Comment by festelo** [comment]
> @festelo wow, cool! I'm gonna test it tomorrow. Thanks!

No problem 👍 
Note, since ticket #2 created there have been two breaking changes in h3_flutter:
1. You can't use `h3` singletone anymore, you should use `const H3Factory().load()`. The same for geojson2h3 - `final geojson2h3 = Geojson2H3(h3)` instead of  global `geojson2h3` singletone.
2. In h3 functions you can't use int anymore, e.g. h3.h3IsValid(0x821C37FFFFFFFFF), you should use BigInt - h3.h3IsValid(BigInt.parse('0x821C37FFFFFFFFF')). That's because flutter web doesn't work well with big numbers
